"""updade_migrations

Revision ID: 43d1a491b9b4
Revises:
Create Date: 2025-10-05 21:15:30.590461
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d1a491b9b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ia_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_title', sa.String(length=255), nullable=False),
        sa.Column('str_filename', sa.String(length=255), nullable=True),
        sa.Column('txt_content', sa.Text(), nullable=False),
        sa.Column('str_content_type', sa.String(length=100), nullable=True),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            'dt_uploaded_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'dt_processed_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('int_size_bytes', sa.Integer(), nullable=True),
        sa.Column('str_content_hash', sa.String(length=64), nullable=True),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_name', sa.String(), nullable=False),
        sa.Column('str_description', sa.String(), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_role_name', 'role', ['str_name'], unique=True)
    op.create_table(
        'transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_name', sa.String(), nullable=False),
        sa.Column('str_description', sa.String(), nullable=False),
        sa.Column('str_operation_code', sa.String(length=7), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_transaction_op_code',
        'transaction',
        ['str_operation_code'],
        unique=True,
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_display_name', sa.String(), nullable=False),
        sa.Column('str_username', sa.String(), nullable=False),
        sa.Column('str_password', sa.String(), nullable=False),
        sa.Column('str_email', sa.String(), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_user_email', 'user', ['str_email'], unique=True)
    op.create_index('idx_user_username', 'user', ['str_username'], unique=True)
    op.create_table(
        'assignment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_user_role', 'assignment', ['user_id', 'role_id'], unique=True
    )
    op.create_table(
        'authorization',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.ForeignKeyConstraint(
            ['transaction_id'],
            ['transaction.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_role_transaction',
        'authorization',
        ['role_id', 'transaction_id'],
        unique=True,
    )
    op.create_table(
        'ia_conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_title', sa.String(length=255), nullable=False),
        sa.Column('str_description', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'dt_started_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'dt_last_message_at', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'paint',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('str_name', sa.String(), nullable=False),
        sa.Column('str_color', sa.String(), nullable=False),
        sa.Column(
            'enum_surface_type',
            sa.Enum(
                'WOOD',
                'METAL',
                'MASONRY',
                'CONCRETE',
                'PLASTER',
                'CERAMIC',
                'GLASS',
                'PLASTIC',
                name='surfacetype',
            ),
            nullable=False,
        ),
        sa.Column(
            'enum_environment',
            sa.Enum('INTERNAL', 'EXTERNAL', 'BOTH', name='environment'),
            nullable=False,
        ),
        sa.Column(
            'enum_finish_type',
            sa.Enum(
                'MATTE',
                'SATIN',
                'SEMI_GLOSS',
                'GLOSS',
                'METALLIC',
                'TEXTURED',
                name='finishtype',
            ),
            nullable=False,
        ),
        sa.Column('str_features', sa.String(length=500), nullable=True),
        sa.Column(
            'enum_paint_line',
            sa.Enum(
                'PREMIUM',
                'STANDARD',
                'ECONOMIC',
                'PROFESSIONAL',
                'SPECIALTY',
                name='paintline',
            ),
            nullable=False,
        ),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by_user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_paint_color', 'paint', ['str_color'], unique=False)
    op.create_index(
        'idx_paint_environment', 'paint', ['enum_environment'], unique=False
    )
    op.create_index(
        'idx_paint_line', 'paint', ['enum_paint_line'], unique=False
    )
    op.create_index('idx_paint_name', 'paint', ['str_name'], unique=False)
    op.create_index(
        'idx_paint_surface_type', 'paint', ['enum_surface_type'], unique=False
    )
    op.create_table(
        'ia_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('txt_content', sa.Text(), nullable=False),
        sa.Column('str_role', sa.String(length=20), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column(
            'dt_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('json_metadata', sa.Text(), nullable=True),
        sa.Column(
            'str_status',
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
        sa.Column(
            'audit_created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column(
            'audit_updated_on',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('audit_user_login', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'],
            ['ia_conversations.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ia_messages')
    op.drop_index('idx_paint_surface_type', table_name='paint')
    op.drop_index('idx_paint_name', table_name='paint')
    op.drop_index('idx_paint_line', table_name='paint')
    op.drop_index('idx_paint_environment', table_name='paint')
    op.drop_index('idx_paint_color', table_name='paint')
    op.drop_table('paint')
    op.drop_table('ia_conversations')
    op.drop_index('idx_role_transaction', table_name='authorization')
    op.drop_table('authorization')
    op.drop_index('idx_user_role', table_name='assignment')
    op.drop_table('assignment')
    op.drop_index('idx_user_username', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('idx_transaction_op_code', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('idx_role_name', table_name='role')
    op.drop_table('role')
    op.drop_table('ia_documents')
    # ### end Alembic commands ###
